import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { Divider, PageHeader, Typography } from 'antd';
import { pageConfig, PageConfigType } from '../lib/pages';
import _ from 'lodash';

const { Title, Paragraph } = Typography;

const Home: NextPage = ({ pageConfig: PageConfigType }) => {
    console.log('pageConfig', pageConfig);

    const rendPageCard = (pageConfig: PageConfigType, realPath: string) => {
        const { title, path, pages } = pageConfig;
        return (
            <div>
                <div className={styles.grid}>
                    {/* TODO 递归遍历这里*/}
                    {_.map(pages, (page, index) => {
                        const { title, path, pages: subPages } = page;
                        return (
                            <div key={index} className={styles.card}>
                                <h2>{title}</h2>
                                {subPages && _.map(subPages, (page, index) => {
                                    const { title, path } = page;
                                    return (
                                        <Paragraph>
                                            <Link href={`${realPath}/${path}`}>
                                                <a>{title}</a>
                                            </Link>
                                        </Paragraph>
                                    );
                                })}
                            </div>
                        );
                    })}
                </div>
            </div>

        );
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>WebGL 学习笔记📒</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <PageHeader
                className="site-page-header"
                title="WebGL 学习笔记📒"
            />
            <main>
                <div className={styles.main}>
                    {_.map(pageConfig, (page, index) => {
                        const { title, path, pages } = page;
                        return (
                            <div key={index}>
                                <Divider orientation="left" plain>
                                    {title}
                                </Divider>
                                <div className={styles.grid}>
                                    {rendPageCard(page, path)}
                                </div>

                            </div>
                        );
                    })}

                    {/*<Divider orientation="left" plain>*/}
                    {/*    WebGPU*/}
                    {/*</Divider>*/}
                </div>
            </main>

        </div>
    );
};



export async function getStaticProps() {
    return {
        props: {
            pageConfig,
        }, // will be passed to the page component as props
    }
}



export default Home;



