import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          WebGL 编程指南笔记
        </h1>

        <p className={styles.description}>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>HelloWebGL &rarr;</h2>
            <Link href="/Hello">
              <a>TranslateRotate</a>
            </Link>
          </div>
          <div className={styles.card}>
            <h2>高级变换与动画基础 &rarr;</h2>
            <Link href="/ch4/TranslateRotate">
              <a>平移，然后旋转</a>
            </Link>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
